---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.15.0@sha256:14ef82daec16838a95d9c414c7f6b4fd0139643a89cfe08e9164dbf2ca6485dc
  replicas: 3
  args:
    - '--proactor_threads=2'
#    - '--hz=1'
  resources:
    requests:
      cpu: 20m
      memory: 2048Mi
    limits:
      memory: 4096Mi
