---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  name: dragonfly
spec:
  image: ghcr.io/dragonflydb/dragonfly:v1.16.0@sha256:27f7e10867075007f304d56e636b9dbaa6c871707f967de33308a1d220373fb3
  replicas: 3
  args:
    - '--proactor_threads=2'
#    - '--hz=1'
  resources:
    requests:
      cpu: 20m
      memory: 2048Mi
    limits:
      memory: 4096Mi
