# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:HFW8YDjusb29N83kAC2W6usiDe6UbLxWvoxA3KVj/RH9ERBl7hob7CgquKzB1BWOR8/+sFLENhh0KvjGX9V1JYkE8pHMtFy5gVbTa5LxTYSO7/22orrP9ubuI2TcA8nyeZn4jfTdx664F7FrIzJ+T9Ot8nALHxUdcSQCmIuO7TXLgZseIC+aHdEaJCEClsZURFLL5+1GURe96RuYhUVWGyXpv7AqdEshwXLy4Xgya5gqppRBfWfpsB6crO0nxHjMpW25oQZoGcd0y4wMRxz1Vsx2Lnel1qJ4KLbXNROcsOxkI+MgVdreFEy6YtbX+i9fsew77jHZn41QCnMDHnNNtGMHE7T2aEdrBs0Xdm5NQh78+3kZbi68BMvcTW7KiwSV0uItwZCEIvZV1nFA8AWeEbdgAwykXY7BXiTwglT1DrcEuLfck7iViEWxggDUmhFj2wrblJ0AWT2KT9rWPYLnUeQVoPjCwrNQCnihOdYLvQqh9kVkCOpVfTbsWAiOIq77bFjXuLH4gUn38d3WPjggttcEr7UNqWa7JmmX1Vd9FOJ3osBGR7Aj8abwHtj2e15+GT9P802ANy+6FkctENf6vYhiOJB0KnqKvTAXXbXTITafVz3kUfGsyGa2Bu+Bie+CRVF8ueYmFb+cskIp2C0GzbP+Y0BjuDiCRUALSO6iRxgkVAF2f1/TYmhH9EVzzmoqi7HccxgkuDMJ9zDT6ti3xFoWRAkK4bZ1/6llIWO72WoMuOJ5xDiAYKjfz5T+9c1KkRA0lgncMvZyhgKebIxzzkQap05oXGE/e9ZDFZhKAcstjozY4nGZPShkSuU0PxS+FUiH/qvqiI6AO5CLs+3ZlFPhblaolPSPlx6DHf8bhOdYjjwDXkOn7SqiONtMyVFn6PsPv1yZAuxMuMz1VrRKO+1n7guwzNrJlkU72oqN2ATfTQiPqQ==,iv:IzuSl/1loRb48PMJvaIHvfs/FZefmzCSSzEobXHej70=,tag:HmNs8lBxdgu9H4ZUhXe2HA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cFdqbmVocFJBS2pCMU4w
            SGIvcWNnbXIyM0hJYmxtcnNFblBnbWg1QndVCnRTQWFWcGMzSGtFVVZEbklXOEg3
            QVgzaThRMUpmS0JZZzZTTUYyYjFuOTgKLS0tIHdVRGZ3ZS9XeVFWUEVhUmNpekpx
            T1JtV2VzOFBrR0FnejZ5US9BQjVFeE0KZ5slJatnc9omzO/ltPMZsXB2impPCxOF
            hXUXxDZEVUuIrWF/eQ25IJyTJCUqpxz4wj4PPrx1ISG60sMjmOpldQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T21:27:08Z"
    mac: ENC[AES256_GCM,data:j0/frvmUc8UOdrnJheJT840hoajcMfhl3yfIHwdGWyVZTSsKwcwUbdE0PSwAinPndpciK8luXW+wy/E2+JuoHg0K3vxPiKUdSfjWP9uLzdntb8eRCY4aKQNP0m8cmcvZBPiUSCmFawkyF4nBe7CQCb9kMqWKqGedqXTWG9YtZIM=,iv:kUTt5L7XKS/g9TGXmwsd/aHlsHNlCXSK5E2TzEuv2T8=,tag:ZZKiUtyAXflxsZC5XebT4Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
