# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:+k5uWdXsQxIxgCCbfmJ2lU3bclTAewEHxAgk6yuHkF5CwX2oWvRvZQFp75UtjdPAB/nAM172HeuQ6fIsJDKza52Qj60+XYGH2e52ERA5Ftkqj/yTrwiach63Bbz+sQ6K6V8oUgZxtVruNKJR048YgWI7RwFQDmCVaGi5HicL+gZawgvAOxLJ4EpFfd8oLra7aTrajgEYVYwsTCZidL9I740kNsYTHGp3WFpaYpknbD2QU4d/Unrq/zfrTaYZbsnzr2wQx3bpTk6USX36glgq2nm5srwcSpoGH2nlXuwMFpetP89nZU+1vgU4ZLBYisxH/bdDX0z4UQmVAKYHap2CdDntQ4oXdmMMfmi4MUChSoNYxq27g+qk/ic9yKvPalB/0E7ljZAd0YGt+G0QFziVsjhLfTeAhIJ3oEUng6hKFvjKNaIqot1bRROph7yMK0kL6UxyBU283RoMfR/8qDRVrsYvxV0ibm6OPD9GZ5XSSIJ7b24cRSw5zlGL8NAcAOlREtJnrnIapB8TZYP0tbtBhKcQLpQPQWIWGgj+ChMBajXYU1D6nd77zUjXFUB2a6xYipGd7jws5QTBcn1oK884HseNDKf3wRO6hkzDlzH7SUI0mrs4bVokLlh9pRD4CEIqf3JD9fbFnfSLzFtaXTpkHDnn1eRY4VDjO2duW4u6H+I8YBOAxSLXSFiBsWDcOK1Ep1ipxMr3fDcvOn0ZDCylGPLO/9lYuPrRDvkcfUrxj3CWYkhWLJj3phtbNDSb8VCTWfhK2aTZVuBPsvAtdUrvsSNReC3WBHsbtKJCbq9HabtiBUZcKPydrVpCALHfB+Axuh95BK0DMRjQ,iv:YZgCQSE243ZsFG/C+YPTG7UCHBuIFek7Q2eEb7Ig8Qk=,tag:HmIxifA84pKdwIpN91Mzfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjNVN5YzZ4cmt3dFY3VWlL
            bHBOZE91S2RIMnRKTW4xdjJUTmhxdGQ3bmdvCi8zVGRGTk1rbkxqbGRzRUNWOXgr
            Zm8xRE9hc1JCWDZSK0x4SzRBVjBRUWcKLS0tIG1xMzBwUHp3L0tIWm1iSnRmeFB0
            VmJidU9aVTFHR0F3L0dnZlpmMnlSTmsKHw1Dbr4K22LHMxjb7lZfRKKx15xhumfD
            6KcgkvFHGr/uH+Nk3vJRuVZrCfOv901fAX4w6kqr9BO9YzRdq93Q/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T21:20:40Z"
    mac: ENC[AES256_GCM,data:WYS66W68czxuqNDX3wnxt5bzqSctC4Sgg2Zj8xlVkz9vO0rCEDs5MUOwEn9mkbwWWN+EgXERma3IMTLrCyYT/NSroNudtpJHNvK00spE/Nr59wKr17/TInaB/tg7IOZ4aZ9aq81xvcjbtq/BkcxZaTheoCyiH+WdWPBgn9Uu0HY=,iv:cbdlTE+KzMNj5YynEAjxpKuQp0AueFGe6Rjn4SKd+iE=,tag:A/UpbY9N+AI39pP+5VaBUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
