# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:9VY4Oqib+juc7r4g47TiPvbg+SWoMR4Jizs6ZK2W1Axdc94ghSHL/f6M/YdOWwPFH2k9pPx+MwZWyXk1XNm/RJ56hnEM62jReAI5B0BAvnUtQKcLqZA41dkJFXPxiHX/CDJxsAgNHl2rUkvugqfmEV0LbKOXi3hLsZRW/5I7gpXJRHCBwRuVNEQoFeWwfLXPfT2MDM5tfco4Zsik+WbZk74FWTrlzyGiQ6JVKV317W1UoNezd6l6LkN2qnLqXpOmbMwrqWOOGsqmL2wSV1Wi/U6DB0IVMDEcWqfqP1/syJ5PhbNt1VwMRr5P5SlIOIr6lpIaSXJAV8zxza/VnwHELsV34+olq2W6ickkkRKIqeIpVgs9R7rOtxv8bIiGKAw0Q2RviL6xVzjsHib0L98czvmfsQg+FUHW+94yJLTf3cE7Tv4OM5wIm7cx9J4X/DQIt4jSPSBNA9jybKGnhkh5vgewK19wOLyNSHIc1bYw5G0v1KnnaGaoipVZqfyM5FUrm5x9VfVACNUWa96+N73ZMgMbLLxlIwRapv3Y7eIQxF5T4YPXnHdNrqT3DCCRv9yUW7o2DDdn8FaDTz2NHZFRLf94tfRkzEjEPB6MRRlTm0RFUlL2rbaQh0W4n8cPElfv1811gKwuUvNd5kySIdzN65U7Yljxc5o3MvimtnUJxqTVKHwEbHGVZWA4TNOHmvCqpnpDqF6DpVjFyRN1rjrCgR/+eADO0/wgy0NJDBu6jawH2Pw92GaSnHM9tLPjl7C7vLfKpFOcz2jXR3KGovqaG1Xy8iT2iSrtHr3TyauJjNs4JyTylA3XRO8dGksXvKyqY9aw5hzI+50ReR/YcMjJl8sWYebmmd9v3kqQHa0PFBrE1+tQd2MnoOLXPy9ZaTbqgnN+znA1CtgdEcyNbc/JEXbSncMuszFfX7Ym3Nx1nhPcSTm6cRI9qDImfF5ud43zCvGZH5jkJE7RMIN5z494ANB0+C9iHh5aSJb0PNXjJrpaXPqv4p9YZSKeKww8BgzHCD1JHgWHACJ08J9ug/hpk4tgiMWoPAGTld6KEJ8673+af0tyDJGaZfHTRiGxZu8D4I7PiaRixcy4UrYrSfnkPgcL92RGjBMYRatg42+551dbEwLNYaGKAEq/NhrzzjxuhFrGT6q8kX7lCFTCtK6+ZQsgMEvdk1AgPygPM1C65E4zYq+EXwCsc/qrvb7FsZzszCluB4fO8LKe4h+N1xNs63CwRifFjPqEZJJozk2YhiUPAjHW5PMCkREMYdM=,iv:nlOt2nnj28vRHw0BJuR2+sPPKvtxn178v8NIvmYYIyc=,tag:R/kDcY6ngicagDzFYGd63g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQnZSMEtoTWQ0ZmE4UzFC
            N3RTMkpHQ0xKYXRySEFGMktnaThOWmt6aDJVCjgzakNubXdyQkk2S29TcXAvbERw
            My9xQWFIODRkelJHeWV1Z3JYN1ZaeWMKLS0tIHFRYkR1b1NEd1BZUkluajY4MTNH
            Nnprazl2WDl5dHRRRDR0TlRPMWdBekkKBDjYIwxP9ROPYl27Xa5/YW+uhOdp1AfJ
            nfsGEd5lkrZ8kmfN63l4z1sjRsHT6E3WcukNMhB1TPJ4DFWZzb+DAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-12T20:59:50Z"
    mac: ENC[AES256_GCM,data:lWjHjUjqbU6eQP03BJyS5HUr4Jfg7agEdXMeSpst87QCuLOhu5Kxdo+IhnZ9TsLFu8BrFkw+TYxNbeHakCIalsRsrPZmWltMt5NVV0/Lal7DHe3Qj+ljM5uOsp7bWtbk5iq+uBlqez2n1a4KPxgKEUa0iLLGhhPKLsEQohe/E1A=,iv:VL6/taMCkkK7nHlmt27klgjk1Jn5HYPyQ30oQbIcOtw=,tag:bYIUv35Ep3C6aA1jevL+cA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
