---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
  data:
    - secretKey: VPN_ENDPOINT_IP
      remoteRef:
        key: qbittorrent
        property: VPN_ENDPOINT_IP
    - secretKey: WIREGUARD_PUBLIC_KEY
      remoteRef:
        key: qbittorrent
        property: WIREGUARD_PUBLIC_KEY
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: qbittorrent
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: VPN_PORT_FORWARDING
      remoteRef:
        key: qbittorrent
        property: VPN_PORT_FORWARDING
    - secretKey: VPN_PORT_FORWARDING_PROVIDER
      remoteRef:
        key: qbittorrent
        property: VPN_PORT_FORWARDING_PROVIDER
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: downloads
        property: VPN_ADDRESSES
    - secretKey: VPN_TYPE
      remoteRef:
        key: downloads
        property: VPN_TYPE
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: downloads
        property: CUSTOM_SECRET_DOMAIN
    - secretKey: VPN_SERVICE_PROVIDER
      remoteRef:
        key: downloads
        property: VPN_SERVICE_PROVIDER
    - secretKey: VPN_INTERFACE
      remoteRef:
        key: downloads
        property: VPN_INTERFACE
    - secretKey: VPN_ENDPOINT_PORT
      remoteRef:
        key: downloads
        property: VPN_ENDPOINT_PORT
