---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      qbittorrent:
        annotations:
          configmap.reloader.stakater.com/reload: qbittorrent-scripts
          secret.reloader.stakater.com/reload: qbittorrent-secret
        pod:
          securityContext:
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 10000
        containers:
          app:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent-beta
              tag: 4.6.4@sha256:f541287a4d1b3f6dbc4ab660a7a7eaedbb14da1e3f8b50a3c4942b54c500abcf
              pullPolicy: IfNotPresent
            env:
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
              QBT_Application__MemoryWorkingSetLimit:
                valueFrom:
                  resourceFieldRef:
                    containerName: qbittorrent
                    resource: limits.memory
                    divisor: 1Mi
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.42.0.0/16, 192.168.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false
              QBT_BitTorrent__Session__Interface: eth0
              QBT_BitTorrent__Session__InterfaceAddress:
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP
              QBT_BitTorrent__Session__InterfaceName: eth0
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 49m
                memory: 1024Mi
              limits:
                memory: 8192Mi
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          gluetun:
            image:
              repository: docker.io/qmcgaw/gluetun
              tag: latest@sha256:bfcf38ffbfbb2f5668e9f718e461b013ca6917129df34ae7a76ad5343fcf35fe
            env:
              FIREWALL_INPUT_PORTS: 8080
              FIREWALL_OUTBOUND_SUBNETS: 10.42.0.0/16,10.43.0.0/16 # Allow access to k8s subnets
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false

          port-forward:
            image:
              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
              tag: v0.0.1@sha256:a520dbcbbe046ccefec51bfcee12b5a1f63d31a800292b9d60f7fc478481815c
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "internal"
        annotations:
          external-dns.powerdns.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: gts-production
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            /outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: qbittorrent-cert

    persistence:
      config:
        existingClaim: qbittorrent-config
        advancedMounts:
          qbittorrent:
            app:
              - path: /config
      scripts:
        type: configMap
        name: qbittorrent-scripts
        defaultMode: 0775
        advancedMounts:
          qbittorrent:
            app:
              - path: /scripts
                readOnly: true
      media:
        type: nfs
        server: 192.168.112.5
        path: /mnt/flashstor/media
        advancedMounts:
          qbittorrent:
            app:
              - path: /media
