apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:y87bIQlAkiYYQC7hLV4SN4OCMQKvR2obq5E9IG8GEFZH2mG0,iv:CGPkhOWvszSm0c2O7TgUcnQFya8DAtZt7TNsD0BtAMY=,tag:lAJGMMqlNXruWrAWK7NbQA==,type:str]
    credentials.json: ENC[AES256_GCM,data:AjJ5orGyW7KOiPE08QevqcnFHxjKgb+zkSYu9zsjIIoZocUMttR7S/ecrFomK3MYWgT8fRx0MrHRn1WW9nVvE4SzbPcJoERhC7fb/Y6Mvyz8mVIHrxskK3F4yGrlqUpcirJRIhYjx7GBuIHIn5lzgbz/rsTF8hGJu5crc+hnFVAXFdTo9NDa/aa0qZUjrrQux9ROWKtJDg/UcOUww8jFn2LnzHqZB2H0J3onj7Ocsw==,iv:aZaadndNEtInWpCYZ0j5gpeaEedUMWuF1ClRKQ9Aux0=,tag:39+0FnP0PZLYxO0pjjMDUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRnBBY0hJY3BNbUZ1VlNY
            a290ZyszVXBteDVtZFBmRVI5VEl0eEltTlVJCnBDRDFHclc4bFBQWVo4eHMvQ3lz
            eGxZSWlMbDQ2dlE3WWZNenBtQStNV1EKLS0tIE5KMnpBZ2Q3K3E3dU9ZbUJmSUZr
            NlAwTWkyTTJieFBIM0NLNDdDa3dqUzAK+RbF80AHKx1SYAjCzY4/MwauNvG7YG85
            k0VsAzzF9sq4z8RgNKobOo8bGYnvIR9HWlcHmHYMx+3F412egRrIcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T17:26:16Z"
    mac: ENC[AES256_GCM,data:b2JUrChw7ptMBGTMvDGEcSRwko+HoHJM2CbZFtzNRWgt7ECe0WLDjGEbYqg8iqv10Y5khGMIlEatNvGHPNE1g2Dr4rpFOAvjUKpX5ZNYNfvdrrfLnoFLbBqHScPT8pFJPJGxLFqtt/gslqe88ddkIdz6eQXyBUGjWT3rwtt7+g8=,iv:QDe9z+K8oMTycLZGIUckE6CEkVi+5y/MK6jzN5WO3aE=,tag:OzMxpyrGFJc5iooEwIm7fw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
