---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name democratic-csi-nfs-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        driver-config-file.yaml: |
          driver: freenas-api-nfs
          httpConnection:
            protocol: http
            host: {{ .TRUENAS_HOST }}
            port: "80"
            apiKey: {{ .API_TOKEN }}
            allowInsecure: true
          zfs:
            datasetProperties:
              "org.freenas:description": "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            datasetParentName: flashstor/k8s-applications
            detachedSnapshotsDatasetParentName: flashstor/k8s-app-snapshots
            datasetEnableQuotas: true
            datasetEnableReservation: false
            datasetPermissionsMode: "0777"
            datasetPermissionsUser: 0
            datasetPermissionsGroup: 0
          nfs:
            shareCommentTemplate: "{{`{{ parameters.[csi.storage.k8s.io/pvc/name] }}`}}"
            shareHost: "{{ .NFS_HOST }}"
            shareAlldirs: false
            shareAllowedHosts: []
            shareAllowedNetworks: ["192.168.112.0/22"]
            shareMaprootUser: root
            shareMaprootGroup: root
            shareMapallUser: ""
            shareMapallGroup: ""
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: democratic-csi-truenas
