---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wallabag
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: RollingUpdate
        pod:
          enableServiceLinks: false
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2@sha256:3436dfbbc2799332a01361e007e3b408d016cfc235261e1caccc65e6edadf516
            envFrom: &envFrom
              - secretRef:
                  name: ${APP}-secret
        containers:
          main:
            image:
              repository: wallabag/wallabag
              tag: 2.6.9@sha256:d482b139bab164afef0e8bbfbeb7c55cd3e10e848b95d7d167e4ffcbc847f4b9
            env:
              SYMFONY__ENV__DOMAIN_NAME: https://${HOSTNAME}
              SYMFONY__ENV__SERVER_NAME: Wallabag
              SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
              SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
              POPULATE_DATABASE: "false"
            envFrom: &envFrom
            resources:
              requests:
                cpu: 12m
                memory: 64M
              limits:
                memory: 256M

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        className: "internal"
        annotations:
          cert-manager.io/cluster-issuer: gts-production
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          external-dns.powerdns.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: /outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: "${HOSTNAME}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - "${HOSTNAME}"
            secretName: ${APP}-cert
