---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chart:
    spec:
      chart: cilium
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      version: 1.15.2
  interval: 30m

  valuesFrom:
    - kind: ConfigMap
      name: cilium-values

  values:
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
          annotations:
            grafana_folder: Cilium
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true

      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: "internal"
          annotations:
            cert-manager.io/cluster-issuer: gts-production
            cert-manager.io/private-key-algorithm: ECDSA
            cert-manager.io/private-key-size: "384"
            external-dns.powerdns.arpa/enabled: "true"
            external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
            nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
            nginx.ingress.kubernetes.io/auth-signin: |-
              /outpost.goauthentik.io/start?rd=$escaped_request_uri
            nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
            nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
          hosts:
            - &host "hubble.${SECRET_DOMAIN}"
          tls:
            - hosts:
                - *host
              secretName: hubble-cert

    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
        annotations:
          grafana_folder: Cilium
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
      annotations:
        grafana_folder: Cilium
