apiVersion: v1
kind: Secret
metadata:
    name: external-dns-pdns-secret
stringData:
    api-token: ENC[AES256_GCM,data:adRQtz/YKyXTd9eUvO6YEa6eHH8=,iv:2v0u6S/2lzGFniqaXTSGx7gCMnL0sqMcb+OakoclLyA=,tag:KtYu6fF2f25uj6QxugBGHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUzZkdjljNHlDamovUmVp
            UnkxcVR5d0pNWUJNWkNHS0NxZXBtNFU3dkhnCjBrUW1jZTAycG0zNlV6NDNkU0wy
            Y2VMMkh2R1dralB5Uk1nMEpFTTlxV1EKLS0tIEsxakV4OUVJVXFPT1pRY09CM0E0
            N3NqSjRTN1MrcnNxcnNJNWluQXNRNjgKRR839spkuQZ5he/8q/AgKVAWgfUHolny
            Thw5gN5QICJfTmxC+yjLPmYlcDNkKZAF575w5BHDR241LHxcNlLEPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-03T03:27:58Z"
    mac: ENC[AES256_GCM,data:dPhhm0aPbSIO0mpx7VMHT9F9eIHhQkycJH8tKMjUWA/ukBVCmBlyXls3k9xsDyNDGyEF+GW8KPDTPIheQJWDGeKMgzLI1N7tI3swDNXGPzrAxNg8L7/PhKN8h9ZwTJp3Qj6wYauSkwS0waTULdi3GK6CAkjPNpVWuN0Wy8GULyU=,iv:TsGQCzma5a+8/yFP1ZyEDqsMGF8ivuH2aHAr7qb8GPY=,tag:8VOTsF1zPTaR3M7geymCbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
