---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.2.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    global:
      podAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret
      storageClass: truenas-iscsi
      deploymentStrategy:
        type: RollingUpdate

    prometheus:
      rules:
        enabled: true

    authentik:
      log_level: info
      error_reporting:
        enabled: false
        send_pii: false

    server:
      envFrom: &envFrom
        - secretRef:
            name: authentik-secret
      podAnnotations:
        secret.reloader.stakater.com/reload:
      initContainers:
        - name: 01-init-db
          image: ghcr.io/onedr0p/postgres-init:16.2@sha256:0db95dfc91792834ce27e7d400c0c2b4032a69b2705ccd04b2a0a215286c85f6
          envFrom: *envFrom
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 5
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          external-dns.home.arpa/enabled: "true"
          external-dns.powerdns.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: gts-production
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        hosts:
          - sso.${SECRET_DOMAIN}
        tls:
          - hosts:
              - sso.${SECRET_DOMAIN}
            secretName: authentik-cert
      metrics:
        prometheus:
          serviceMonitor:
            enabled: true

    worker:
      envFrom: *envFrom
      initContainers:
        - name: 01-init-db
          image: ghcr.io/onedr0p/postgres-init:16.2@sha256:0db95dfc91792834ce27e7d400c0c2b4032a69b2705ccd04b2a0a215286c85f6
          envFrom: *envFrom
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 5

    postgresql:
      enabled: false

    redis:
      enabled: false
