apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:3WrivTpZlXDTmoeE0vvVhiqRwDuYs5FUdPI98F9/sp3ErJlXZQLrpA==,iv:hxTgZZeDNLltD7Fb0Rpw7BtSv+X1KzGGz0y/nSkNVYU=,tag:8hYpcCmj5IeYeCy0XUpdRA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVENmUnpGSmhkU2lXK2o2
            SXpHenQ3cXhOeXdLMXNSVXkzUDhXdHRUT0YwCitWeE1Sc0hMcTJVVElCVnpaR29w
            VkNhRk5vSHVCQkk3REJMTlFOS0llWGsKLS0tIHBDMU4vZ2plRi9Ga2JwU3RwMHB2
            Y1ZFUGZhV0o1R24xR0daejJUVFA1d2MKtA0UKvwI/GkLr0WriXlwkEIbEPqV8HFJ
            FGV51+hLLfqi0uBiJ/jd598AaORf8slBphuKwvrrvmvQIjRVDHSRYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-04T05:15:52Z"
    mac: ENC[AES256_GCM,data:bKExvgHPdwXWxE50B4Gkr9lFwu+clx/TZuptlDnLbwlHQ4OapB7ZHOfL+guF/zKmnmflBbfHINXjdF8LJ0tQ464+RXnSr3PaC4jFDUKgQ6KTqWh6uiE09JVANt9MQHr01GzMDcALr6PMcqWHQG+S3/l0LHHQ5LD9wKby1W4rPoM=,iv:+aYC7ND+FcXd/KQTMJXiXmxXb9fbF7Fnrl9FRORwrPI=,tag:AHwshVsm5C7qjSr0/stMjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
