---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sabnzbd
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/reload: sabnzbd-secret
        pod:
          securityContext:
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 10000
        containers:
          main:
            nameOverride: sabnzbd
            image:
              repository: ghcr.io/onedr0p/sabnzbd
              tag: 4.2.2@sha256:5b1f15c8d25afa2342505492486361d4ecf14449e1453aeea45cd7c1e5eeb63a
            env:
              TZ: America/New_York
              SABNZBD__PORT: &port 80
              SABNZBD__HOST_WHITELIST_ENTRIES: >-
                sabnzbd,
                sabnzbd.downloads,
                sabnzbd.downloads.svc,
                sabnzbd.downloads.svc.cluster,
                sabnzbd.downloads.svc.cluster.local,
                sabnzbd.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: sabnzbd-secret
            resources:
              requests:
                cpu: 5m
                memory: "1024M"
              limits:
                memory: "4096M"
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
          gluetun:
            image:
              repository: docker.io/qmcgaw/gluetun
              tag: latest@sha256:b1ad4d0b12f6ca703eab97bf391b4e2bfeb134ee9c16d03d8c0e60bf47f544b3
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false
            env:
              - name: VPN_INTERFACE
                value: wg0
              - name: VPN_ENDPOINT_PORT
                value: "51820"
              - name: FIREWALL_INPUT_PORTS
                value: "80"
              - name: FIREWALL_OUTBOUND_SUBNETS
                # Allow access to k8s subnets
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: WIREGUARD_PRIVATE_KEY
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: WIREGUARD_PRIVATE_KEY
              - name: WIREGUARD_PUBLIC_KEY
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: WIREGUARD_PUBLIC_KEY
              - name: WIREGUARD_ADDRESSES
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: WIREGUARD_ADDRESSES
              - name: VPN_SERVICE_PROVIDER
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: VPN_SERVICE_PROVIDER
              - name: VPN_TYPE
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: VPN_TYPE
              - name: VPN_ENDPOINT_IP
                valueFrom:
                  secretKeyRef:
                    name: sabnzbd-secret
                    key: VPN_ENDPOINT_IP

    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          external-dns.powerdns.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
          cert-manager.io/cluster-issuer: gts-production
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            /outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host "sabnzbd.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sabnzbd-cert

    persistence:
      config:
        enabled: true
        existingClaim: sabnzbd-config
      media:
        type: nfs
        server: 192.168.112.5
        path: /mnt/flashstor/media
        globalMounts:
          - path: /media
      temp:
        type: emptyDir
        advancedMounts:
          main:
            main:
              - path: /tmp
