---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ./helmrelease.yaml
  - ./gatus.yaml
  - ./externalsecret.yaml
  - ./volsync.yaml
  - ./pvc.yaml
#  - ./networkpolicy.yaml
  - ./sabnzbd-volsync-restore.yaml
configMapGenerator:
  - name: sabnzbd-dnsdist
    files:
      - ./config/dnsdist.conf
  - name: sabnzbd-resolv
    files:
      - ./config/resolv.conf
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
