---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "sabnzbd-config-copy"
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "sabnzbd-restic-secret"
    cacheStorageClassName: "openebs-hostpath"
    cacheCapacity: "1Gi"
    storageClassName: "truenas-iscsi"
    volumeSnapshotClassName: "truenas-iscsi"
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    accessModes:
      - "ReadWriteOnce"
    capacity: "2Gi"
    destinationPVC: sabnzbd-config
    copyMethod: Direct
