---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      sonarr:
        annotations:
          configmap.reloader.stakater.com/reload: sonarr-dnsdist, sonarr-resolv, sonarr-configmap
          secret.reloader.stakater.com/reload: sonarr-secret
        pod:
          securityContext:
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 10000
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.2@sha256:930a20e3ea8c82504d8e80f413d042d9936930d625fb098dd306b5aad427a151
            envFrom: &envFrom
              - secretRef:
                  name: sonarr-secret
        containers:
          app:
            nameOverride: sonarr
            image:
              repository: ghcr.io/onedr0p/sonarr-develop
              tag: 4.0.2.1312@sha256:9c057693302722de595fcf1a61a49c0bc63d08481d438ec08cd69c74fbad8cb7
              pullPolicy: IfNotPresent
            env:
              TZ: America/New_York
              PUSHOVER_DEBUG: "false"
              COMPlus_EnableDiagnostics: "0"
              SONARR__AUTHENTICATION_METHOD: External
              SONARR__AUTHENTICATION_REQUIRED: DisabledForLocalAddresses
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: &port 80
              SONARR__LOG_LEVEL: info
              SONARR__THEME: dark
            envFrom: *envFrom
            resources:
              requests:
                cpu: 20m
                memory: 512M
              limits:
                memory: 768M
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          gluetun:
            image:
              repository: docker.io/qmcgaw/gluetun
              tag: latest@sha256:b1ad4d0b12f6ca703eab97bf391b4e2bfeb134ee9c16d03d8c0e60bf47f544b3
            env:
              - name: FIREWALL_INPUT_PORTS
                value: "80"
              - name: FIREWALL_OUTBOUND_SUBNETS
                # Allow access to k8s subnets
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: SHADOWSOCKS
                value: "on"
              - name: DOT
                value: "off"
              - name: DNS_SERVER
                value: "127.0.0.2"
              - name: HEALTH_TARGET_ADDRESS
                value: 1.1.1.1:443
            envFrom:
              - secretRef:
                  name: sonarr-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false


          dnsdist:
            image:
              repository: docker.io/powerdns/dnsdist-18
              tag: 1.8.3@sha256:5f2e92f6363db2bd5bd40319ac2fb10e3a583f6ff5fb5d96a948d9c8b93299b3
            securityContext:
              runAsUser: ${APP_UID}
              runAsGroup: ${APP_GID}
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: sonarr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: "internal"
        annotations:
          cert-manager.io/cluster-issuer: gts-production
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          external-dns.home.arpa/enabled: "true"
          external-dns.powerdns.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            /outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: sonarr-cert

    persistence:
      config:
        existingClaim: sonarr-config

      pushover-notify:
        type: configMap
        name: sonarr-configmap
        defaultMode: 0775
        globalMounts:
          - path: /scripts/pushover-notify.sh
            subPath: pushover-notify.sh
            readOnly: true

      tmp:
        type: emptyDir

      media:
        type: nfs
        server: 192.168.112.5
        path: /mnt/flashstor/media
        globalMounts:
          - path: /media

      dnsdist-config:
        type: configMap
        name: sonarr-dnsdist
        advancedMounts:
          sonarr:
            dnsdist:
              - path: /etc/dnsdist/dnsdist.conf
                subPath: dnsdist.conf
                readOnly: true

      sonarr-resolv-config:
        type: configMap
        name: sonarr-resolv
        advancedMounts:
          sonarr:
            app:
              - path: /etc/resolv.conf
                subPath: resolv.conf
                readOnly: true
