---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app awx-operator
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cert-manager-issuers
    - name: external-secrets-stores
  path: "./kubernetes/apps/selfhosted/awx/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app awx-customization
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: awx-operator
    - name: authentik
  path: "./kubernetes/apps/selfhosted/awx/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
