apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-gts-secret
stringData:
    api-token: ENC[AES256_GCM,data:sOcnCHsn3+t/qcz5RjCoZ59QNBG70Xm6VvqECJ9pLLugV6EE86ZYlA==,iv:PRF9toucjdyspRgBr2EkrTtUYkDgoQBG+1QjtuXkm34=,tag:k9lMv+XVJe3yRqylPddTAw==,type:str]
data:
    secret: ENC[AES256_GCM,data:HUtkq3DROeAnPO3PZUvxUWZr7AthmCc5qBBPh5LcRnUIR7L72x0Jkh6JekwefsIVV9EiAtBSVTGEMlC0tOcxOJxVhr4QsTPa73tgY5S+elXiQ4Ok7JtvifeM+tC38JJjcUbnL2bv3FxtkUxp7ILyGe+hrys=,iv:wSm69DiExt66OF7pM2mA+fukb5TqclsJ4At2i+An5L0=,tag:f5MmHU3k7is4A+Y235jwVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRzNOeS9hdWtyYk9jVUtp
            SU44b1JRNTlIbEYrWjN6eFhRc3QxZGhFcHh3CnZOUlN1U2RnMUVMV3NvUHdjTHp3
            K01ZM011NGFCL0FwbkE2WHZWSkVWTVkKLS0tIFRqbWdwUXRGclZuellOYnpSTFpB
            VkJhOXNSYTc2d2wwanI1cFJFclJEZ3cKBj7AdlaRN8Xpb12i2wr21tr7yaUcbozu
            oplLj07hTYQlCcHd8VgmtS0x1A4ODQWoT7iwC5xjPOnlWG2WS9vVeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T20:50:38Z"
    mac: ENC[AES256_GCM,data:05lPuhgPDDBPg+y5cy/1V4OOONiz8LI8rSnYFsWzpcghE2cADhpJMNCbmfLw3z2+LX/bM7h/EfXM/IT/NDs1/wfB09+7W/8BLFiYtGFi9sy4d9eSQXg+QTzo587kRQJC7gtWJXLWHD9MPqVKGuRhLuCL2MGQUheFGfUxmsoHO6c=,iv:6FrAbQTapHWTHS5koWRsA5iaaOeFN0edDsHVI/TimL4=,tag:eVN0ZOvZJRK9agQX2seARA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
