apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-gts-secret
stringData:
    api-token: ENC[AES256_GCM,data:J1hKR5yiZsozH2tWZnaBawtRtbJ9Yk1ezW5pHAIfORJDFrMkfSQrFw==,iv:eh/cfPY2gzmf3FGzoCqv4q6yX1/TMurmtLtcqVK3ldQ=,tag:hi2lFohb8SHn36gutvSCqQ==,type:str]
data:
    secret: ENC[AES256_GCM,data:mZ9j7e6K3kkKZDJK/IGpRM4PtNZ3VsmbCwl0kBH8Qq+SVDrCVx3gC7WgJZPf2fXPbbqqCtp3xV6M+Ebgwhp/nhXg3nYFtAnUpp4ZZsSeIF0vbQEDDfGonNtLARn6DuvDqxS4xLgkgocmuWhDe/ZURyx/lo0=,iv:Dsx4GuFaixUt/sICs1NhiHhFpq1GRvTn2rdTunzZC8s=,tag:qjF2lbCb+Jy+kvyFOZjbsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMzQxaDBLNlRoTTlCekNY
            Wnc5N0hnMXNvYUtvUEQ1N0szUjArWXQ2RGxVClRUSDcwT2s0UC9yaDVxMGJWb05v
            bVp4aFI0OWkyTUg3elVwT25Pc3NCWEUKLS0tIG16YTZMeXQ0MjEvUjhhOG9uTGVr
            ZXNlNEx6OENBeElTcDVuNE9PWnVIMFEK871gUAvm6B7ETYe9GWk+JhwmUOSVO7LD
            ZUZgS0YAEYJhRdgrXTGnUK3FzS5XdMFI88hc9lciRaiKrb3I3qHAhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T00:04:05Z"
    mac: ENC[AES256_GCM,data:18/ZX/5cGwsV9494KLbM0wPVCN9IAMEBe6sAwxpLnn9clILlJ+gNPYIxLckCU0knQuVKmt6omb3V752O32dBFRBqcwHPm4SIbBv9gs2OdMKFMRF8ATJCVi9N9PJT0qH83JblXet1FzAcomUtoUIgGARJrEs1pwp6GPQRnjrLrv4=,iv:azrfzO1zE9LYKV1DDJ6PBLrMHsaFmy5zXSRFkWVeTsc=,tag:CoS92bL5pWgTvYADHgQQKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
