apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: network
stringData:
    api-token: ENC[AES256_GCM,data:gATRzt28WNYlyYSmZZzt0oGMA3Tosexi8Me9B6OxPCx5Qu8uaFiP3w==,iv:m83y9I2JuMwEnBWJ6kZqyR+eFg5D3b3kN/rb2SCCfS8=,tag:WUtG072rNcFl4NmRG0AHzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRjQxQ29kVDJQQ3ExbDRk
            Q0pzSlBwVmFnK1RLN1V1Q0RwYzRINU5PY1I4CkwzWXpDb2UzL2hxZk5raTJzeit5
            b0VwaExlaC9HM1VXbldRK2QwaitCR0UKLS0tIFBhQ2xlL254bnlGdVlneVhNcjlF
            TG94YmdjQ1p3UDdyeEw2TURFSVNLTzgK/tNEtCVBazlUjWzNOB8+PvNjf0uoXB2f
            pH60FeyE+/gstEwTo7MCL/CrlJ5yFjAsTwYgn8n9sutCYgzYX5ODoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-02T20:56:29Z"
    mac: ENC[AES256_GCM,data:ZlQpoBjYvlzW0qXCd5zObF9fHuJsMWvyvFVHKKhqRiGYICFu0+RAkPnAMy/AV4t98GwYnFXPdIfyTD0QhrxIOKxj/6dQr76UvX4TejnxksN/o1KsKsARAHThjZmGvVjxMXQ59V/PlnRKf3wDATt1dz5R1VUOQwPDHL210z3zP/s=,iv:5cna0TcUZGKcEBmjHIm9/1+yDyRzNzPItyDDqCogTkM=,tag:ugwz8PjkXWOarv+2gVc7XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
