apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:82DUlKV2vjnqYwYSpw==,iv:BC7mb/BQYfxzhr3uvElOhBxg+cWsiy0oylFHLDjggEE=,tag:9dkWmXI0AOvPh+6TlWldzg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:oAunzGad7VjR1sNENmA=,iv:rNSFqGmoRLKBTOTozvQZfXQy90T8GBqJyq64P8uXmeg=,tag:wp0Pfdv4R9ZoyJyPA/Uhvw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:qxzUUxPdckvlKzo4aD54KajxecuBQG3rpSCVQHpQLZBeOazY,iv:Q3B1v4ry543uzzXzg+GlNuEbEccVWxdaUvqrDZkjAOw=,tag:btJm5Ydrt9S0reHRfvl3bQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:JzhElTTnS4RVJ7iL9bqOfMBHIuzI,iv:ERXZHwWwdBbmZ52WwZfnpsTXXRnB3wTjBFUthkaECRk=,tag:JCNg8QbxXgyx/pcCdfapvA==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:OBes/xVpkHA=,iv:TcKY4h2kXWbT+MOE7RcZ2sM9Rl5/ioXamG2xfTVfuXc=,tag:zPFRhYib7ZTAI5zLw0cx6w==,type:str]
    SECRET_SMTP_RELAY: ENC[AES256_GCM,data:oIocrc5W91JPirM7HKZR84pgv94=,iv:VU8bju1CmG8JtoMkL0pfYkQx7Xi/H5YWDUFo7xLBOJM=,tag:Yq8y+vSfp2jvubTlrBC7bQ==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:V+0eHiKl21kkMOQ7ITXtkrPw6qIFSlJzBhEXctU3g5Q=,iv:Mts+laR2w1nVnv+fm3a9RW/my/byzF61QxALWLOL6zY=,tag:CObBKldYUmxb2aviVuijUw==,type:str]
    EABkeyID: ENC[AES256_GCM,data:A1gINUQH0XZmRvxd/9P93CBG9YorQyFxQuG8wGy51e0=,iv:GhuBLd0AjzsQxxnv5wfxUAvOzyU3S2qhgRV0/3SXAbQ=,tag:Quu8FmdHJ+9orisrpUPXKA==,type:str]
    CERT_SERVER: ENC[AES256_GCM,data:7gQDhp7OZ2gqNBN+1IjXypXTOm1BBl383n2yCM5iGgqtgNQ/KyQvEQTF,iv:Sxv5jGffaQv0Lj8J+BpPNWUKYsTYntRtOd3o2kNuut4=,tag:KI/V+R4FSRZdQEw6ggLjMg==,type:str]
    KUBERNETES_DASH_TOKEN: ENC[AES256_GCM,data:Cj1R5NUPACBQYp961AF6jQLEZfEterk0Fer+VWP1STYsu4uBGXPTUino8vqsg0e6Icu0sCvfP2Q+pe6F3XC0CsnOb5YKvYeSOXF6O93EMMUm6zD1MGEtcmlxD0KhUF38SXr7IFaibWqGZH9ktmSwlwqP2mRax+tArEoP1BVNvbwzKyMVf3mcEF9wBK3hLi9UDPC4Wz7m+p0PdMnKuoSig0bOlPpcuMppvSR+0YhgBlxndBuYDchGpaQfOKwk1vkqdoRnAQGHKlhALUruOGoek+KoUUjOzCoMBiGg3wH0jOE7lkADVtEgrEBjrDI+oQbvmHGoXmT65BcVKE4mt+bom9qfhy1GxdgcngccJ7ESOy3G/nScfEx2C9dd/jUQ2wNwy4XL6NCT+gvRDLVQIvHYhZdXuvGutiquJYujOwD7BSI9S/Og8SJu+6WUixMGRr09PFEaw/mPtZpFWhX4RacBPwHiBvEPc6kz9OPhkaiaQiHyE5yi/8gS1KBHpi58QRMV1T0TJnlG25yY5aBGdS28/KaYUY4vEU6LzuauAWGSyIkftHhqA0hZRIMtv7mZ2GHlT3uLnHIXjGcR0r+GnakqJm7BHNYCtLZvhfuwJiSKTekHb94nHg/ycyrLt1IO8Vt63Z0DgW/IfGstY48tPhlG0NVAQs+VQr+WZjiflsv9LdO6C6VJT9zjzQBiBomW2ldIPyPTyviqBoER7eZ2t2FVvwyVbVRUPIYI997wN04VE4RHfvuj9G07hDopcP3pKwn9JErh4zzBiPZBnjuPmNVlUNHJu73EwvuYmJtoZWd5Ht6FAfLNcmxgsBi3rbENwZyLPIFfl2LRJgqi6VbXg5xkewnurgtpx+anHiIdCh/gjVRwVbWF7UuGfRXd3ctt9YRFG19bEwyY6gVDLC/2O0RBN0G0LhduDs6pEbxPQh+bdTglsn/vRHxiV1H2ie9uMvPQhpBqcyqPv0G5pQJxCPr/glxQZ8ox/wrP/SroiVXCe0pjoXnTco8CZei65kVGyIzO8/aB3fBpDEyDTFAg96/Q0pl+0gPwZxh6kxfUF6zMmbFMzcAcdREeUPCiUy6X9qA7qaH2ArmbR17xMgT85vgTM3ZKcMiIlI9b4p68rM13Q+odDhHAscAnHpVGQl4FAg4gM5ZtwhkCTxe0xh+F+2gDv+3ZdsKJw4h3TLoDp9T3goFIAxvNMkzdKYTCh3MmeixGyRUfVJ9uOWwdmPu/42gTxCifowRlgbDYFU6k8ygYJf4=,iv:0LjLFJh0fSCb4LxLAVIP4Pho5JGrUjiaxN8b/cjipBw=,tag:ShLVSrm/IFiTKx7hDR9fng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwR012dmxQdHNBeW5LWGdL
            UmxEVWpVdlFIQVE0QUdoTlJWcGhVenBaTFRvCkpOa25jT29nWi9BRHl5QjJ2Y3hj
            K25sSDF6RlIvempnS0s0YzliV2hIaDgKLS0tIGgwaUVMOUtvQjdNcGpteVJDNi9X
            VTI1K01zeW5STm8wQzQzUkdjRnpPMWsKjpm/Zzw1iOkSEkc2KBq7h8fE3pImAd7b
            P6aCVjIu7+08+MynDbUw+hoX+2rrlJsA5YBI3pA/CHGYgKTjHZHJTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T00:02:10Z"
    mac: ENC[AES256_GCM,data:bOmJwVoVswnw8TmIb1WDvZChpLTOLvsnMHYdFMRnLUWFal/i8JDcKiPNQuWDh49Y1e4dO7HSCE3wb2vjadH0RswMKEvh5wpR/1jatKWp6lMGKYyJzeHSzaaMhTRNv5U7ayggOkaMFCkf98T/420zafrfvx45vHak2hL/rXeHd9k=,iv:ughiL5bJ9doK8dqwHOgd01y1ODOy6tvlZu/qQVTkRKI=,tag:3uqu8ZWwYsMCw801iWCImw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
