apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:e3drREqRs+rNvkbBv7+pQaAteeD7NIftPp+Pm8IQ/tHjNUYPU45GgysQVITMWKclKphWYrr5OXnuljMMkvIiz9nEQRhB63OVjvA4FhwfcjrXuPkpwBQenu+Lh+LTMg==,iv:dBL/1lnin2BPPHMrkAPgvbLVsjNdW4vGW9mTVHHoYQY=,tag:f24YBzalSRO2m0EAuvP78w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:eLtZ34RcWOYUwR1Cug==,iv:jz2JdesOBqTQG+NMa4XRnpJpWdBIVEQqGXfgbhZvUEg=,tag:6BX1aucbSwLuBdFimiRj9Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:37nCaueYhZMDRYZfuKY=,iv:gSx5XV+GgCjiTrcVqpSaHz3Xz5CJ+Om/jvchnoU0dsM=,tag:RxfMkI6safFN/WoLC3y1Rw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:eHCwAUSazjPZ0XnhidfwRQR3wJyRluIhQFi6tHjYIQe6s+Vt,iv:zdTImJERZQqP/Ku10G85RpBMSUitFBq4ahXMRe8zLII=,tag:MlbcSTC5onRghhkFDsifHw==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:D8ZTHeO++CuYDk/do9Ebdon2RgWaYbzwCaE=,iv:Z9XguV4/S7yTXts/P5rXPvlHdphVrK7xZdklV46eDm8=,tag:BhLU13rAbdoWrdKavq2qcQ==,type:str]
    SECRET_EMAIL_DOMAIN: ENC[AES256_GCM,data:EggZHpz+85A=,iv:bL5Zrm7DrWuHFRWh2ecD9UpyJPbXgHNy82DW+JUW+qg=,tag:zMxltZHn6j3wbSHWY4P28A==,type:str]
    SECRET_SMTP_RELAY: ENC[AES256_GCM,data:GOtoZq4wNsjpN9IbqlFJYUj2Ws4=,iv:mvcPovLKdgY+7vBkhbaykAEouBPrQiEmxOaDZXeVG0U=,tag:+8D83b8wb4Ak9pmM81iq9g==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:+Rpz4Gie0MB3BC9Oqj8URu1pqGyaNcQvhki1Cc7SwwM=,iv:MB7N2CeeXZNKY+N5b5gU0BK71rRO6voY9lzyStWP+Wc=,tag:ABlH8DfzaAg92r66k13dPA==,type:str]
    EABkeyID: ENC[AES256_GCM,data:NeJmFu8KdCq5/E/HDtYhtfp0968tdSeuRX+uEP4tWe0=,iv:VQYY8l8MK4gf3SD5Y+RESiOGw/Frdrnn9RAjrIXl33Y=,tag:JK4OmXoUypAqhSF1BYDxLA==,type:str]
    CERT_SERVER: ENC[AES256_GCM,data:oa+nY8tjsYVeGZDZHLST+A737A7VwLd1Qc39lP7J2MNrmDnLntT+d0Pd,iv:BBWb2X9ycvqviLgVxhBCnvcjQUAtdsViY935o6y2ZNU=,tag:gIrSr77ahZGLf0tHCdR7ew==,type:str]
    KUBERNETES_DASH_TOKEN: ENC[AES256_GCM,data:Fu2TpyIx0KY4sL5svlaEIkvSBIK6K8WSBGORlfLACmQ6BLwpUotIwu6gYJJLP4lbBuT+QHwkn07IVG5QxtQAO4UZi7UXy8GdHzhluyFtlyNa4HKykCdArB+a3KZEayuhFXpKA+bVCrdRJmSSGxq9HS+gXs26za6333cDmVPVLKUrNrxlm4nNJnLtWIGfFJRHWrZhX0noepozgty4fsr90iiMbjxb9pOBJeKdVOYGze1xwayaCuR0v9Frd5fg+6ktg9QLQTJPYCTroHp25hzGhWIKcCR53BZ3oXX4TCXTfvkBE3/vchDrRcQZtrbofFNGYf7rOztuqD0efBxSTGiRhw9Rh9h4zIafgrWW1W24EqgVW5j9CYt680XL/5dAU6/0NhaOPWAufRKQ+dYbl+0pN4xnRIsb7LCAvCNX5dIyBXx9NII8pBZ4woyaml+68SBh35b5Ae40rb2dpV7N1pYzKSmy09m+1ZAY8XKstvLP8vpmyK8SNTJdbzdKJgb9nv3FDZkmnEdVqF7MSCaoGXvisf4AWZfTJRHNwuiQGhVtz/LswXXaV3lGNvbuhKkdwR4o1p5BN8QWAul9TNvGh6p80YuM/uD2OsIf4foNObQloe7+a7IemyI1ATl4EA5PsaHiQojUnuhR0SuEZ3D+H3pkfKwAQzXoSR16p3sYpggetnxIg97tipndh8ymUhRDM9vt8r7f5u0Ad3kbZGLwuIuMmVh8uYppWV86JJ5CIEOzc/B80+XLINsCI/9fLKA5cZo21619D7hagyvjbHWDp69JBra0mAXnzl9YcYy3225aujpUsuZJ2TKDMziZVkcCHrWolFFWVrqtNJECWOHMhY5ZxLoxMkdd2APDYiim7UqQZafh3er3bs8/EKCPMIwePksNstBdZTdjBTKOIBeGUKaSakC5czoVFrBCCBNfCZ7zKPEDWZDnfdzTZchAoaoee/1vtCft4tmeK40ciHzFfBQpBdlgsMFCmUCrfUsI+HRFu29Pm2yti3gBnYOSIvRPFYx2pnt6nEoL04hMDDB624fNzxE56hB/JM9FOxeLWu3yaViCaZmpshy1pEz8Puk65aAIIbowvvvY2FOAl2nOU+8En8fKJcnzI4f5apbO+YcQH4kGiXkKR1qe+ozIs5JW85DXN8PXQszyjjsrOsoCi7cmuE7sPi9OwfKLsakAn6ZJeqtFkfvbzNINUnz1d92PoThBQdzs5XCTrOhDzCgR/w1FDIbBYDtzEQG6DHFKHYH6b6s=,iv:caJ9ziMYolZqJzhpBT3a9/KTvvaToFULtJKlogwSymQ=,tag:+YmJ/wcVgV4m4HFydjs5TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweEljTVYvd1BPVFp5QmR3
            cFpRcHNvM1YxSlhTZlRDb04vT2FtNFEvUlVjCjFPdm5WS3JLbzRWSUJ3WmlXVkRG
            WWc5V2RodTdXN2lLZklrVUU0SEpyVTQKLS0tIFhNTHNUSmV6SWgxTDEzZU9OaUpq
            YUpzQ1NDT2Z5Ni9ldy9idFJJeE52eVkKQnx+CjGOWd7qtU8Uw3nikYnJsm9pTkuJ
            yeGZo8lF9xg5bog7v8XE3iBqjWK4ReMgTECH5A+LJHf+LIdrPUsFOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-14T20:48:56Z"
    mac: ENC[AES256_GCM,data:eeoXEeq4i36HuzaqurovrWkoQ4Y7BgNNY6iLzPzoMuOPShdBbrD5vtCVkWkrrXWSZUlgd6EKp+G54/J/hJcwMp37GTUxHhKlHoRCNDY6vowZRYHfVgE5hPUeLm/OoFDsnCW1nIwSq3Xh6bJb+4kWSK6rCxmcI8pbZychRk1x8gs=,iv:bzfQouaVIMD2iyZ6UznqCb+YQmm0Q67tLtECzLUVIII=,tag:BLOXtyA8vMz4C2u6nMfTRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
