---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app plex
spec:
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          nodeSelector:
            nvidia.com/gpu.present: "true"
          runtimeClassName: nvidia
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups: [44, 105, 10000]

        containers:
          app:
            nameOverride: plex
            image:
              repository: ghcr.io/onedr0p/plex
              tag: 1.40.1.8227-c0dd5a73e@sha256:a60bc6352543b4453b117a8f2b89549e458f3ed8960206d2f3501756b6beb519
            env:
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                nvidia.com/gpu: 1  # Request 1 GPU
                cpu: 100m
                memory: 4Gi
              limits:
                nvidia.com/gpu: 1  # Limit to 1 GPU
                memory: 12Gi

    service:
      app:
        controller: plex
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          io.cilium/lb-ipam-ips: "192.168.254.15"
        ports:
          http:
            port: 32400

    ingress:
      app:
        annotations:
          cert-manager.io/cluster-issuer: gts-production
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "384"
          external-dns.home.arpa/enabled: "true"
          external-dns.powerdns.arpa/enabled: "true"
          external-dns.alpha.kubernetes.io/target: ingress.${SECRET_DOMAIN}
        className: "internal"
        hosts:
          - host: &host plex.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: plex-cert

    persistence:
      config:
        existingClaim: config-plex-0
        advancedMounts:
          plex:
            app:
              - path: /config

      logs:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /config/Library/Application Support/Plex Media Server/Logs

      plex-media:
        type: nfs
        server: 192.168.112.5
        path: /mnt/flashstor/media
        advancedMounts:
          plex:
            app:
              - path: /plex-media

      transcode:
        type: emptyDir
        advancedMounts:
          plex:
            app:
              - path: /transcode
