---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-plex-0
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Gi
  storageClassName: "truenas-iscsi"
