---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.20.2
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      create: true
    image:
      repository: ghcr.io/cloudnative-pg/cloudnative-pg
      pullPolicy: IfNotPresent
      tag: "1.23.2@sha256:f1f3c20f3637be5a8d1d702a55b6d25719e6b4ca63d1b56473e7ecec83157fde"
