---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kube-vip
spec:
  staticConfigs:
    - targets:
        - 192.168.112.41:2112
        - 192.168.112.42:2112
        - 192.168.112.43:2112
        - 192.168.112.44:2112
        - 192.168.112.45:2112
  metricsPath: /metrics
