apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:/qSQgegS/Vl0sKBOShoE7WA9jfUFFjl2le9RyVy1snA=,iv:nzUcJ+K/0EkXH3KMhkdwp32A4Nbpgc/rGRRHLNb35Ao=,tag:RUuDE4+YzxUUmK8/m3w4ug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5ld9zkz3xprgff704uh7l6kv90cklzhpynvjvz7ks7pmpatuf8s52rvjx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNW9mWDU4MzEzRlZUOHJR
            MnFvREFjSC9jb3lOVkZuNWVxQ1QzaDh1elJ3CnJacXlHUFpCTXZCZ1p3TUM4TFNz
            VGxDeUJ2eUd2d1BHVUs5VTFnR2NKdlUKLS0tIGRWMHdZNXdsS1A5U0w1bFAraG04
            L1AwNk1FLzEzWElTK29ublhuUlgwOGMK5LtpSaEPfPHhDzj2MHFUPE2/+VG63luC
            qO90RrM/+lZgV1QfT11/rsLbx09jIBIVM83L29w3hwOIOHMz7Jkc1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T17:58:40Z"
    mac: ENC[AES256_GCM,data:E4ncCqRfhgMSkXvnN4E7eGkRlZaX/WLszWJH7DNR14xCg0r1JJAmo4GfiEnfvQSeIs7HJu1uPE3jnA0XMsME+VrjqsTbtgjr0/gPfzHLde8tdNnmL0UylUwEB24GeXw7dfyQxMGx8pS/sVlq5OfV/WcI8CqsMArG5BibkkS48js=,iv:Qa14HcZYQ7s7fz5THthEqscUGOSz4H7vRHkJCLbqnIk=,tag:BYGyQ3TRannFRRdPucuR0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
